application:
  download: ${user.dir}/downloads # Directory where downloaded files are saved. By default, current directory.

spring:
  application:
    name: genefinder

rest:
  timeout: 120000

ncbi:
  refseq-protein-accession-pattern: "^(?:ref\\|)?([ANYXZ]P_\\d+\\.\\d+)"
  refseq-protein-gi-pattern: "^(?:gi\\|)?(\\d+)"
  eutils: https://eutils.ncbi.nlm.nih.gov/entrez/eutils
  maxIdsPerRequest: 1000 # Never more than 5000, see https://www.ncbi.nlm.nih.gov/books/NBK25498/#chapter3.Application_4_Finding_unique_se

uniprot:
  mapping: http://www.uniprot.org/uploadlists
  proteinIdPattern: "^(?:\\w{2}\\|)?([OPQ][0-9][A-Z0-9]{3}[0-9])(?:-\\d+)?(?:\\|.*)?|^(?:\\w{2}\\|)?([A-NR-Z][0-9]([A-Z][A-Z0-9]{2}[0-9]){1,2})(?:-\\d+)?(?:\\|.*)?"
  maxIdsPerRequest: 100 # Never more than 500

logging:
  file: ${spring.application.name}.log

---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb

logging:
  file: test.log
