application:
  download: ${user.dir}/downloads # Directory where downloaded files are saved. By default, current directory.

spring:
  application:
    name: genefinder
# Database.
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./genefinder
    username: test
    password: 
    tomcat:
      test-on-borrow: true
      validationQuery: SELECT 1

ncbi:
  ftp: ftp.ncbi.nlm.nih.gov
  taxonomy: /pub/taxonomy/taxdmp.zip
  taxonomyNodes: nodes.dmp
  geneInfo: /gene/DATA/gene_info.gz

uniprot:
  ftp: ftp.uniprot.org
  referenceProteomes: /pub/databases/uniprot/current_release/knowledgebase/reference_proteomes
  filenamePattern: "UP\\d+_(\\d+)[\\._].+"
  giMapping: GI
  refseqMapping: RefSeq
  taxonMapping: NCBI_TaxID
  geneMapping: GeneID
  proteinIdPattern: "^(?:\\w{2}\\|)?([OPQ][0-9][A-Z0-9]{3}[0-9])(?:-\\d+)?(?:\\|.*)?|^(?:\\w{2}\\|)?([A-NR-Z][0-9]([A-Z][A-Z0-9]{2}[0-9]){1,2})(?:-\\d+)?(?:\\|.*)?"

logging:
  file: ${spring.application.name}.log

---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb

logging:
  file: test.log
